### ISSUE TITLE
Room name with space

### ISSUE THREAD

**Issue by luckyraul** [apertureless/mina-hipchat#1]
URI::InvalidURIError: bad URI(is not URI?): https://api.hipchat.com/v2/room/Mygento Devel/notification?auth_token=XXXXXXXXXXXXXXXXX

**Comment by apertureless** [comment]
Yeah, I don't have an url encoder implemented.

Try Mygento%20Devel as the room name.

**Comment by luckyraul** [comment]
Okay, Let me try. 
 Also I have a question why you don't use official library https://github.com/hipchat/hipchat-rb ?)

**Comment by apertureless** [comment]
Okay. Let me know if it works.

Well, there is no particular reason. I think back then I simply didn't saw that there is a ruby package for the api.

**Comment by luckyraul** [comment]
There was no error, but nothing appeared in hipchat

**Comment by apertureless** [comment]
okay, i'm gonna look into it

**Comment by apertureless** [comment]
Looks like HipChat changed some stuff, since then.

But you can simply use the **room id** instead of the room name. This will work, even if you have spaces in the name. You find the room id in the url of your room or if you add an integration it will show the complete api call uri, with room id and auth key.

**Comment by luckyraul** [comment]
Are you going to rewrite with the official gem?

**Comment by apertureless** [comment]
No, not really. I switched to slack a while ago and not using HipChat anymore. 
But feel to fork it and change it to the official api wrapper gem.
